Mobile/Models/Task/Log/Task_Log_Data.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
namespace Mobile
{
    public class Task_Log_Data
    {
        public static List<Task_Log_Model> List(string PartnerNumber, out string Message)
        {
            DataTable zTable = new DataTable();
            string zSQL = "SELECT * FROM CRM_Task_Log WHERE RecordStatus != 99 AND PartnerNumber = @PartnerNumber ";
            string zConnectionString = Helper.ConnectionString;
            try
            {
                SqlConnection zConnect = new SqlConnection(zConnectionString);
                zConnect.Open();
                SqlCommand zCommand = new SqlCommand(zSQL, zConnect);
                zCommand.Parameters.Add("@PartnerNumber", SqlDbType.NVarChar).Value = PartnerNumber;
                SqlDataAdapter zAdapter = new SqlDataAdapter(zCommand);
                zAdapter.Fill(zTable);
                zCommand.Dispose();
                zConnect.Close(); Message = string.Empty;
            }
            catch (Exception ex)
            {
                Message = ex.ToString();
            }
            List<Task_Log_Model> zList = new List<Task_Log_Model>();
            foreach (DataRow r in zTable.Rows)
            {
                zList.Add(new Task_Log_Model()
                {
                    AutoKey = r["AutoKey"].ToInt(),
                    TaskKey = r["TaskKey"].ToString(),
                    CategoryKey = r["CategoryKey"].ToString(),
                    JsonData = r["JsonData"].ToString(),
                    CreatedOn = (r["CreatedOn"] == DBNull.Value ? DateTime.MinValue : (DateTime)r["CreatedOn"]),
                    CreatedBy = r["CreatedBy"].ToString(),
                    CreatedName = r["CreatedName"].ToString(),
                    ModifiedOn = (r["ModifiedOn"] == DBNull.Value ? DateTime.MinValue : (DateTime)r["ModifiedOn"]),
                    ModifiedBy = r["ModifiedBy"].ToString(),
                    ModifiedName = r["ModifiedName"].ToString(),
                });
            }
            return zList;
        }
    }
}

Mobile/Models/Task/Log/Task_Log_Info.cs
using System;
using System.Data;
using System.Data.SqlClient;
namespace Mobile
{
    public class Task_Log_Info
    {

        public Task_Log_Model Task_Log = new Task_Log_Model();
        private string _Message = "";
        public string Code
        {
            get
            {
                if (_Message.Length >= 3)
                {
                    return _Message.Substring(0, 3);
                }
                else
                {
                    return "";
                }
            }
        }
        public string Message
        {
            get { return _Message; }
            set { _Message = value; }
        }

        #region [ Constructor Get Information ]
        public Task_Log_Info()
        {
        }
        public Task_Log_Info(int AutoKey)
        {
            string zSQL = "SELECT * FROM CRM_Task_Log WHERE AutoKey = @AutoKey AND RecordStatus != 99 ";
            string zConnectionString = Helper.ConnectionString;
            SqlConnection zConnect = new SqlConnection(zConnectionString);
            zConnect.Open();
            try
            {
                SqlCommand zCommand = new SqlCommand(zSQL, zConnect);
                zCommand.CommandType = CommandType.Text;
                zCommand.Parameters.Add("@AutoKey", SqlDbType.Int).Value = AutoKey;
                SqlDataReader zReader = zCommand.ExecuteReader();
                if (zReader.HasRows)
                {
                    zReader.Read();
                    if (zReader["AutoKey"] != DBNull.Value)
                    {
                        Task_Log.AutoKey = int.Parse(zReader["AutoKey"].ToString());
                    }

                    Task_Log.TaskKey = zReader["TaskKey"].ToString();
                    Task_Log.CategoryKey = zReader["CategoryKey"].ToString();
                    Task_Log.JsonData = zReader["JsonData"].ToString();
                    if (zReader["CreatedOn"] != DBNull.Value)
                    {
                        Task_Log.CreatedOn = (DateTime)zReader["CreatedOn"];
                    }

                    Task_Log.CreatedBy = zReader["CreatedBy"].ToString();
                    Task_Log.CreatedName = zReader["CreatedName"].ToString();
                    if (zReader["ModifiedOn"] != DBNull.Value)
                    {
                        Task_Log.ModifiedOn = (DateTime)zReader["ModifiedOn"];
                    }

                    Task_Log.ModifiedBy = zReader["ModifiedBy"].ToString();
                    Task_Log.ModifiedName = zReader["ModifiedName"].ToString();
                    _Message = "200 OK";
                }
                else
                {
                    _Message = "404 Not Found";
                }
                zReader.Close();
                zCommand.Dispose();
            }
            catch (Exception Err)
            {
                _Message = "500 " + Err.ToString();
            }
            finally
            {
                zConnect.Close();
            }
        }

        #endregion

        #region [ Constructor Update Information ]

        public string Create_ServerKey()
        {
            //---------- String SQL Access Database ---------------
            string zSQL = "INSERT INTO CRM_Task_Log ("
         + " TaskKey , CategoryKey, CategoryName, StatusKey, StatusName, Description, JsonData , CreatedBy , CreatedName , ModifiedBy , ModifiedName ) "
         + " VALUES ( "
         + " @TaskKey , @CategoryKey, @CategoryName, @StatusKey, @StatusName, @Description, @JsonData , @CreatedBy , @CreatedName , @ModifiedBy , @ModifiedName ) ";
            string zResult = "";
            string zConnectionString = Helper.ConnectionString;
            SqlConnection zConnect = new SqlConnection(zConnectionString);
            zConnect.Open();
            try
            {
                SqlCommand zCommand = new SqlCommand(zSQL, zConnect);
                zCommand.CommandType = CommandType.Text;
                zCommand.Parameters.Add("@TaskKey", SqlDbType.NVarChar).Value = Task_Log.TaskKey;
                zCommand.Parameters.Add("@CategoryKey", SqlDbType.NVarChar).Value = Task_Log.CategoryKey;
                zCommand.Parameters.Add("@CategoryName", SqlDbType.NVarChar).Value = Task_Log.CategoryName;
                zCommand.Parameters.Add("@StatusKey", SqlDbType.NVarChar).Value = Task_Log.StatusKey;
                zCommand.Parameters.Add("@StatusName", SqlDbType.NVarChar).Value = Task_Log.StatusName;
                zCommand.Parameters.Add("@Description", SqlDbType.NVarChar).Value = Task_Log.Description;
                zCommand.Parameters.Add("@JsonData", SqlDbType.NVarChar).Value = Task_Log.JsonData;
                zCommand.Parameters.Add("@CreatedBy", SqlDbType.NVarChar).Value = Task_Log.CreatedBy;
                zCommand.Parameters.Add("@CreatedName", SqlDbType.NVarChar).Value = Task_Log.CreatedName;
                zCommand.Parameters.Add("@ModifiedBy", SqlDbType.NVarChar).Value = Task_Log.ModifiedBy;
                zCommand.Parameters.Add("@ModifiedName", SqlDbType.NVarChar).Value = Task_Log.ModifiedName;
                zResult = zCommand.ExecuteNonQuery().ToString();
                zCommand.Dispose();
                _Message = "201 Created";
            }
            catch (Exception Err)
            {
                _Message = "500 " + Err.ToString();
            }
            finally
            {
                zConnect.Close();
            }
            return zResult;
        }        
        #endregion
    }
}

Mobile/Controllers/TaskController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace Mobile.Controllers
{
    public class TaskController : BaseController
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Default()
        {
            return View();
        }

        //--------------Ngoai cua hang
        #region ---OutSite---
        public IActionResult OutSite_List(int CategoryKey)
        {
            var List = new List<Task_Model>();
            string Message = "";

            //kỹ thuật
            if (CategoryKey > 26)
            {
                if (UserLog.Employee.PositionKey == 54)
                {
                    List = Task_Data.Personal(UserLog.PartnerNumber, CategoryKey, UserLog.UserKey, out Message);
                    ViewBag.ListData = List;
                }
                else
                {
                    List = Task_Data.List(UserLog.PartnerNumber, CategoryKey, UserLog.DataAccess, out Message);
                    ViewBag.ListData = List;
                }
            }
            else
            {
                List = Task_Data.List(UserLog.PartnerNumber, CategoryKey, string.Empty, out Message);
                ViewBag.ListData = List;
            }

            ViewBag.ListData = List;
            ViewBag.ActiveCate = CategoryKey;
            ViewBag.Message = Message;
            return View("~/Views/Task/OutSite/List.cshtml");
        }
        public IActionResult OutSite_Detail(string TaskKey)
        {
            ViewBag.ListEmployee = Employee_Data.List(UserLog.PartnerNumber);

            TaskKey = TaskKey ?? "";
            var zTitle = "";
            var zTask = new Task_Model();
            if (TaskKey != string.Empty)
            {
                var zInfo = new Task_Info(TaskKey);
                zTask = zInfo.Task;
                zTitle = "Chi tiết";
            }
            int CategoryKey = zTask.CategoryKey;
            string btnAction = "";
            switch (CategoryKey)
            {
                case 26:
                    btnAction += @"<button id='btnYes' type='button' class='btn-sm btn btn-primary float-right'><i class='fas fa-check'></i> Nhận việc</button>";
                    break;

                case 27:
                    if (UserLog.UserKey == "7fa5dc11-e327-4636-a3a1-8af49dc8415a")
                    {
                        btnAction += @"<button id='btnChange' type='button' class='btn-sm btn btn-primary'><i class='fas fa-exchange-alt'></i> Đổi người</button>";
                    }

                    if (zTask.Style == "SM")
                    {
                        btnAction += @"<button id='btnYes' type='button' class='btn-sm btn btn-primary float-right'><i class='fas fa-check'></i> Đã sửa xong</button>";
                        btnAction += @"<button id='btnNo' type='button' class='btn-sm btn btn-primary float-right mr-1'><i class='fas fa-stop-circle'></i> Lấy máy về</button>";
                    }
                    else
                    {
                        btnAction += @"<button id='btnYes' type='button' class='btn-sm btn btn-primary float-right'><i class='fas fa-check'></i> Đã giao xong</button>";
                    }
                    break;

                    //case 28:
                    //    btnAction += @"<button id='btnYes' type='button' class='btn-sm btn btn-primary float-right'><i class='fas fa-check'></i>Đã sửa xong</button>";
                    //    btnAction += @"<button id='btnNo' type='button' class='btn-sm btn btn-primary float-right mr-1'><i class='fas fa-stop-circle'></i>Không sửa được</button>";
                    //    break;

                    //case 29:
                    //    btnAction += @"<button id='btnYes' type='button' class='btn-sm btn btn-primary float-right'><i class='fas fa-check'></i>Đã giao</button>";
                    //    break;
            }
            ViewBag.Button = btnAction;
            ViewBag.TitleTask = zTitle;
            return View("~/Views/Task/OutSite/Detail.cshtml", zTask);
        }
        public IActionResult OutSite_Edit(string TaskKey)
        {
            ViewBag.ListCustomer = Customer_Data.List(UserLog.PartnerNumber, out string Message);

            TaskKey = TaskKey ?? "";
            var zTitle = "";
            var zTask = new Task_Model();
            if (TaskKey != string.Empty)
            {
                var zInfo = new Task_Info(TaskKey);
                zTask = zInfo.Task;
                zTitle = "Chỉnh sửa";
            }
            else
            {
                zTask.CategoryKey = 26;
                zTitle = "Tạo mới";
            }

            ViewBag.TitleTask = zTitle;
            return View("~/Views/Task/OutSite/Edit.cshtml", zTask);
        }
        public IActionResult OutSite_Process(string TaskKey, int CategoryKey, int Status, string FixNote, string AutoTask, string Todo)
        {
            FixNote = FixNote ?? "";
            var zResult = new ServerResult();
            var zInfo = new Task_Info(TaskKey);
            string zSQL = "UPDATE CRM_Task SET ";
            string StatusName = "";
            string CategoryName = "";

            switch (CategoryKey)
            {
                case 26:     //1. Việc mới    1 - Nhận việc   
                    {
                        if (Status == 1)
                        {
                            StatusName = "Nhận việc";
                            CategoryKey = CategoryKey + 1;
                            CategoryName = Task_Data.TaskCategoryName(UserLog.PartnerNumber, CategoryKey);
                            zSQL += "";
                            zSQL += "StartDate = GETDATE(), ";
                            zSQL += "StatusKey = " + Status + ", ";
                            zSQL += "StatusName = N'" + StatusName + "', ";
                            zSQL += "CategoryKey = " + CategoryKey + ", ";
                            zSQL += "CategoryName = N'" + CategoryName + "', ";
                            zSQL += "OwnerBy = N'" + UserLog.UserKey + "', ";
                            zSQL += "OwnerName = N'" + UserLog.Employee.FullName + "', ";
                            zSQL += "OwnerKey = '" + UserLog.Employee.EmployeeKey + "', ";
                            zSQL += "OwnerPhone = '" + UserLog.Employee.MobiPhone + "', ";
                            zSQL += "BranchKey = '" + UserLog.Employee.BranchKey + "', ";
                        }
                    }
                    break;

                case 27:    //2. Giao máy/ đi sửa		1 - Giao xong/ sửa xong 	0 - nhận máy về
                    {
                        if (Status == 1)
                        {
                            if (zInfo.Task.Style == "GH")
                            {
                                StatusName = "Giao xong";
                                CategoryKey = 30;
                                CategoryName = Task_Data.TaskCategoryName(UserLog.PartnerNumber, CategoryKey);

                                zSQL += "CodeLine= 'Y',";
                                zSQL += "StatusKey = " + Status + ", ";
                                zSQL += "StatusName = N'" + StatusName + "', ";
                                zSQL += "CategoryKey = " + CategoryKey + ", ";
                                zSQL += "CategoryName = N'" + CategoryName + "', ";
                            }
                            if (zInfo.Task.Style == "SM")
                            {
                                StatusName = "Sửa xong";
                                CategoryKey = 30;
                                CategoryName = Task_Data.TaskCategoryName(UserLog.PartnerNumber, CategoryKey);
                                zSQL += "CodeLine= 'Y',";
                                zSQL += "StatusKey = " + Status + ", ";
                                zSQL += "StatusName = N'" + StatusName + "', ";
                                zSQL += "CategoryKey = " + CategoryKey + ", ";
                                zSQL += "CategoryName = N'" + CategoryName + "', ";
                                zSQL += "ToDo = N'" + Todo + "', ";
                            }
                        }
                        else
                        {
                            if (zInfo.Task.Style == "SM")
                            {
                                StatusName = "Không thể sửa tại chỗ khách";
                                CategoryKey = 30;
                                CategoryName = Task_Data.TaskCategoryName(UserLog.PartnerNumber, CategoryKey);
                                zSQL += "CodeLine= 'N',";
                                zSQL += "Note = N'" + FixNote + "', ";
                                zSQL += "StatusKey = " + Status + ", ";
                                zSQL += "StatusName = N'" + StatusName + "', ";
                                zSQL += "CategoryKey = " + CategoryKey + ", ";
                                zSQL += "CategoryName = N'" + CategoryName + "', ";
                            }
                        }
                    }
                    break;

                case 28:    //3. Nhận máy về    1 - Sửa xong
                    {
                        if (Status == 1)
                        {
                            StatusName = "Sửa xong";
                            CategoryKey = CategoryKey + 1;
                            CategoryName = Task_Data.TaskCategoryName(UserLog.PartnerNumber, CategoryKey);
                            zSQL += "ToDo = N'" + Todo + "', ";
                            zSQL += "CodeLine= 'Y',";
                            zSQL += "StatusKey = " + Status + ", ";
                            zSQL += "StatusName = N'" + StatusName + "', ";
                            zSQL += "CategoryKey = " + CategoryKey + ", ";

Mobile/Views/Task/InPlace/Edit.cshtml
@using Microsoft.AspNetCore.Http
@using Newtonsoft.Json
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Task/_Layout.cshtml";

    var session = Context.Session.GetString("UserLogged");
    var UserLog = JsonConvert.DeserializeObject<User_Model>(session);
    var _ListBranch = new List<Branch_Model>();
    if (ViewBag.ListBranch != null)
    {
        _ListBranch = ViewBag.ListBranch as List<Branch_Model>;
    }
}
<header class="header">
    <div class="task-header">
        <table class="table table-sm mb-0"
               style="
    border-bottom: 1px solid #2196f3;
    color: gray;">
            <tr>
                <td class="text-center" style="vertical-align: middle; width:15%">
                    <a asp-controller="Task" asp-action="InPlace_List" id="goBack">
                        <i class="fas fa-2x fa-angle-left"></i>
                    </a>
                </td>
                <td class="text-center" style="vertical-align: middle;">
                    <h4 class="">Công việc tại cửa hàng</h4>
                </td>
                <td class="text-center" style="vertical-align: middle; width:15%"></td>
            </tr>
        </table>
    </div>
</header>
<form class="inner-wrapper" method="post" asp-controller="Task" asp-action="InPlace_Save" onsubmit="return CheckSave()">
    <section class="card border">
        <div class="card-header">
            <h4 class="card-title text-center m-0">@ViewBag.TitleTask</h4>
        </div>
        <div class="card-body">
            @if (TempData["error"] != null)
            {
                <div class="alert alert-danger">
                    <strong>@TempData["error"] !</strong>.
                </div>
            }

            <div class="form-horizontal form-bordered">

                <!-- itmayhan, sdt a Thong -->
                @if (UserLog.UserKey == "7fa5dc11-e327-4636-a3a1-8af49dc8415a" ||
                    UserLog.UserKey == "8c9dccf5-8cca-468c-b9a3-c140dcfd5b22")
                {
                    <div class="form-group-sm">
                        <div class="checkbox-custom checkbox-danger">
                            <input type="checkbox" id="chkClass" name="Class" value="UT">
                            <label for="chkClass">Hàng mang về</label>
                        </div>
                    </div>
                }
                <div class="form-group-sm row">
                    <label class="col-lg-3 control-label text-lg-right pt-2" for="txt_Phone">Cửa hàng/ chi nhánh</label>
                    <div class="col-lg-6">
                        <select class="form-control" name="Branch">
                            <option value="">--//--</option>
                            @foreach (var item in _ListBranch)
                            {
                                <option value="@item.BranchKey">@item.BranchName</option>
                            }
                        </select>
                    </div>
                </div>
                <div class="form-group-sm row">
                    <label class="col-lg-3 control-label text-lg-right pt-2" for="txt_Phone">Số điện thoại</label>
                    <div class="col-lg-6">
                        <input type="number" class="form-control" id="txt_Phone" name="CustomerPhone" value="@Model.CustomerPhone">
                    </div>
                </div>
                <div class="form-group-sm row">
                    <label class="col-lg-3 control-label text-lg-right pt-2" for="txt_CustomerName">
                        Nhập tên khách hàng
                    </label>
                    <div class="col-lg-6">
                        <input type="text" class="form-control" id="txt_CustomerName" name="CustomerName" value="@Model.CustomerName.ToUpper()">
                    </div>
                </div>
                <div class="form-group-sm row">
                    <label class="col-lg-3 control-label text-lg-right pt-2" for="txt_Address">Địa chỉ</label>
                    <div class="col-lg-6">
                        <input type="text" class="form-control" id="txt_Address" name="CustomerAddress" value="@Model.CustomerAddress">
                    </div>
                </div>
                <div class="form-group-sm row">
                    <label class="col-lg-3 control-label text-lg-right pt-2" for="txt_Description">Nội dung</label>
                    <div class="col-lg-6">
                        <textarea type="text" class="form-control" id="txt_Description" rows="4" name="TaskContent">@Model.TaskContent</textarea>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            @if (Model.TaskKey.Length >= 36)
            {
                <button type="button" class="btn btn-danger" onclick="Delete('@Model.TaskKey')">
                    <i class="fa fa-trash"></i> Xóa
                </button>
            }
            <button type="button" class="btn btn-default go-back">
                <i class="fas fa-times"></i>
                Trở lại
            </button>
            <button type="submit" class="btn btn-primary float-right">
                <i class="fas fa-paper-plane"></i>
                Gửi/ cập nhật
            </button>
        </div>
    </section>
    <input id="txt_Class" type="hidden" name="Class" value="@Model.Class" />
    <input id="txt_TaskKey" type="hidden" name="TaskKey" value="@Model.TaskKey" />
    <input id="txt_CategoryKey" type="hidden" name="CategoryKey" value="@Model.CategoryKey" />
    <input id="txt_CustomerKey" type="hidden" name="CustomerKey" value="@Model.CustomerKey" />
</form>

@section scripts{
    <script>
        var URL_GetCustomer = "@Url.Action("Get_CustomerPhone", "Task")";
        var URL_Delete = "@Url.Action("Delete", "Task")";
        var URL_List = "@Url.Action("InPlace_List", "Task")";
    </script>
    <script>
        $(document).ready(function () {
            $("#txt_Phone").blur(function () {
                GetCustomer();
            });
            $("#goBack").click(function (e) {
                e.preventDefault();
                window.location = URL_List + "?CategoryKey=" + $("#txt_CategoryKey").val();
            });

            var cls = $("#txt_Class").val();
            if (cls === "UT") {
                $("#chkClass").prop('checked', true);
            }
        });

        function CheckSave() {
            if ($('#chkClass').is(':checked')) {
                $("#txt_Class").val("UT");
            }
            else {
                $("#txt_Class").val("BT");
            }

            var input = $("#txt_CustomerName").val();
            if (input === "" || input === undefined) {
                Utils.OpenNotify("Bạn phải nhập tên khách hàng !.", "Thông báo", "error");
                $("#txt_CustomerName").focus();
                $("#txt_CustomerName").css({ "background": "lightcoral" });
                return false;
            }
            else {
                $("#txt_CustomerName").css({ "background": "white" });
            }

            input = $("#txt_Phone").val();
            if (input === "" || input === undefined) {
                Utils.OpenNotify("Bạn phải nhập số điện thoại khách hàng !.", "Thông báo", "error");
                $("#txt_Phone").focus();
                $("#txt_Phone").css({ "background": "lightcoral" });
                return false;
            }
            else {
                $("#txt_Phone").css({ "background": "white" });
            }

            input = $("#txt_Address").val();
            if (input === "" || input === undefined) {
                Utils.OpenNotify("Bạn phải nhập địa chỉ khách hàng !.", "Thông báo", "error");
                $("#txt_Address").focus();
                $("#txt_Address").css({ "background": "lightcoral" });
                return false;
            }
            else {
                $("#txt_Address").css({ "background": "white" });
            }

            input = $("#txt_Description").val();
            if (input === "" || input === undefined) {
                Utils.OpenNotify("Bạn phải nhập nội dung thông tin !.", "Thông báo", "error");
                $("#txt_Description").focus();
                $("#txt_Description").css({ "background": "lightcoral" });
                return false;
            }
            else {
                $("#txt_Description").css({ "background": "white" });
            }

            return true;
        }
        function GetCustomer() {
            var Phone = $("#txt_Phone").val();
            if (Phone.length >= 10) {
                $.ajax({
                    url: URL_GetCustomer,
                    type: "GET",
                    data: {
                        "Phone": Phone
                    },
                    beforeSend: function () {

                    },
                    success: function (r) {
                        if (r.success) {
                            var obj = JSON.parse(r.data);
                            $("#txt_CustomerName").val(obj.FullName);
                            $("#txt_Address").val(obj.Address);
                            $("#txt_CustomerKey").val(obj.CustomerKey);
                        }
                    },
                    error: function (err) {
                        Utils.OpenNotify("Thông báo", err.responseText, "error");
                    },
                    complete: function () {

                    }
                });
            }
        }
        function Delete(id) {
            $.confirm({
                type: "red",
                typeAnimated: true,
                title: "Cảnh báo !.",
                content: "Bạn có chắc xóa thông tin này ?.",
                buttons: {
                    confirm: {
                        text: "Đồng ý",
                        btnClass: "btn-red",
                        action: function () {
                            $.ajax({
                                url: URL_Delete,
                                type: "POST",
                                data: {
                                    "TaskKey": id
                                },
                                beforeSend: function () {

                                },
                                success: function (r) {
                                    if (r.success) {
                                        window.location = URL_List + "?CategoryKey=" + $("#txt_CategoryKey").val();
                                    }
                                    else {
                                        Utils.OpenNotify("Thông báo", r.Message, "error");
                                    }
                                },
                                error: function (err) {
                                    Utils.OpenNotify("Thông báo", err.responseText, "error");
                                },
                                complete: function () {

                                }
                            });
                        }
                    },
                    cancel: {
                        text: "Hủy",
                    }
                }
            });
        }
    </script>
}