Mobile/Controllers/AuthController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace Mobile.Controllers
{
    public class AuthController : Controller
    {
        private readonly string _Partner = "99AF7431-AE45-4F47-9D17-4560C10255A8";

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SignIn()
        {
            if (Request.Cookies["username"] != null &&
                Request.Cookies["password"] != null)
            {
                ViewBag.UserName = Request.Cookies["username"];
                ViewBag.Password = Request.Cookies["password"];
            }

            ViewBag.ListBranch = Branch_Data.List(_Partner);
            ViewBag.Message = "NotAuthen";
            return View("~/Views/Auth/SignIn.cshtml");
        }
        [HttpPost]
        public IActionResult SignIn(string UserName, string Password)
        {
            ViewBag.ListBranch = Branch_Data.List(_Partner);
            User_Info zInfo = new User_Info(UserName, Password);
            if (zInfo.Code == "200")
            {
                //check time
                // if (DateTime.Now.Hour < 8 ||
                //     DateTime.Now.Hour > 17)
                // {
                //     ViewBag.Message = "TimeOut";
                //     return View("~/Views/Auth/SignIn.cshtml");
                // }

                ViewBag.Message = "IsAuthen";

                //Get Partner
                var zUser = zInfo.User;
                zUser.Partner = new Partner_Info(zUser.PartnerNumber).Partner;

                //Get Employee
                var zEmployeeKey = zUser.Employee.EmployeeKey;
                if (zEmployeeKey != string.Empty)
                {
                    zUser.Employee = new Employee_Info(zEmployeeKey).Employee;
                }

                //get data access
                string temp = zInfo.User.DataAccess;
                if (temp != null && temp != string.Empty)
                {
                    var zList = JsonConvert.DeserializeObject<List<string>>(temp);
                    string zData = zList.ToStringComma();
                    zUser.DataAccess = zData;
                }

                //get role access
                zInfo.User.ListRole = User_Data.ReadUserRole(zUser.PartnerNumber, zInfo.User.UserKey, out string Message);

                // Save session
                var key = "UserLogged";
                var obj = JsonConvert.SerializeObject(zUser);
                HttpContext.Session.SetString(key, obj);

                //Update Logged
                zInfo.UpdateLogged();

                //set cookies
                Response.Cookies.Append("username", UserName,
                    new CookieOptions
                    {
                        Expires = DateTime.Now.AddDays(15),
                        IsEssential = true
                    });

                Response.Cookies.Append("password", Password,
                    new CookieOptions
                    {
                        Expires = DateTime.Now.AddDays(15),
                        IsEssential = true
                    });
            }
            else
            {
                ViewBag.Message = "405";
            }

            return RedirectToAction("Index", "Home");

            //return View("~/Views/Auth/SignIn.cshtml");
        }

        public IActionResult SignOut()
        {
            ViewBag.ListBranch = Branch_Data.List(_Partner);
            if (Request.Cookies["username"] != null &&
               Request.Cookies["password"] != null)
            {
                ViewBag.UserName = Request.Cookies["username"];
                ViewBag.Password = Request.Cookies["password"];
            }

            HttpContext.Session.Clear();
            return View("~/Views/Auth/SignIn.cshtml");
        }

        [HttpPost]
        public IActionResult Register(string Phone, string Password, string Name, string Address, string Branch)
        {
            var CheckPhone = new Employee_Info(Phone, _Partner);
            if (CheckPhone.Code == "200" ||
                CheckPhone.Code == "201")
            {
                ViewBag.Message = "Số điện thoại này đã được sử dụng, Bạn phải nhập số khác !.";
                return View("~/Views/Auth/SignIn.cshtml");
            }

            string NewKey = Guid.NewGuid().ToString();
            var zManager = Employee_Data.GetManager(_Partner, Branch, out string Message);

            var zInfo = new Employee_Info();
            var zModel = new Employee_Model
            {
                EmployeeKey = NewKey,
                BranchKey = Branch.ToInt(),
                ReportToKey = zManager.EmployeeKey,
                ReportToName = zManager.FullName,
                FirstName = Name,
                AddressContact = Address,
                MobiPhone = Phone,

                PartnerNumber = _Partner,
                Password = TN_Utils.HashPass(Password),

                CreatedName = UriHelper.GetEncodedUrl(Request),
                ModifiedName = UriHelper.GetEncodedUrl(Request),
            };

            zInfo.Employee.ClearNullable();
            zInfo.Employee = zModel;
            zInfo.Create_ClientKey();
            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                var zUser = new User_Info();
                zUser.User.Employee = zInfo.Employee;
                zUser.User.UserName = Phone;
                zUser.User.Password = TN_Utils.HashPass(Password);
                zUser.User.PartnerNumber = _Partner;
                zUser.User.ExpireDate = DateTime.Now.AddYears(1);
                zUser.User.Activate = true;
                zUser.User.CreatedName = UriHelper.GetEncodedUrl(Request);
                zUser.User.ModifiedName = UriHelper.GetEncodedUrl(Request);
                zUser.Create_ServerKey();

                // Save session
                var key = "UserLogged";
                var obj = JsonConvert.SerializeObject(zUser.User);
                HttpContext.Session.SetString(key, obj);

                ViewBag.Message = "IsAuthen";

                return RedirectToAction("Index", "Home");
            }

            ViewBag.Message = zInfo.Message.GetFirstLine();
            return View("~/Views/Auth/SignIn.cshtml");
        }

        public JsonResult CheckPhone(string Phone)
        {
            var zResult = new ServerResult();
            var zInfo = new Employee_Info(Phone, _Partner);
            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                zResult.Success = true;
                zResult.Data = JsonConvert.SerializeObject(zInfo.Employee);
            }
            else
            {
                zResult.Success = false;
                zResult.Message = "";
            }
            return Json(zResult);
        }
    }
}

Mobile/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
    <title>App</title>
    <!-- Web Fonts  -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">
    <!-- themes/vendor CSS -->
    <link rel="stylesheet" href="@Url.Content("~/assets/themes/vendor/bootstrap/css/bootstrap.css")" />
    <link rel="stylesheet" href="@Url.Content("~/assets/themes/vendor/animate/animate.css")" />
    <link rel="stylesheet" href="@Url.Content("~/assets/themes/vendor/font-awesome/css/all.min.css")" />
    <link rel="stylesheet" href="@Url.Content("~/assets/themes/vendor/jstree/themes/default/style.css")" />
    <!-- Specific Page themes/vendor CSS -->
    <link rel="stylesheet" href="@Url.Content("~/assets/themes/vendor/jquery-ui/jquery-ui.css")" />
    <link rel="stylesheet" href="@Url.Content("~/assets/themes/vendor/jquery-ui/jquery-ui.theme.css")" />
    <link rel="stylesheet" href="@Url.Content("~/assets/themes/vendor/jquery-confirm/css/jquery-confirm.css")" />
    <link rel="stylesheet" href="@Url.Content("~/assets/themes/vendor/magnific-popup/magnific-popup.css")" />
    <link rel="stylesheet" href="@Url.Content("~/assets/themes/vendor/select2/css/select2.css")" />
    <link rel="stylesheet" href="@Url.Content("~/assets/themes/vendor/bootstrap-datepicker/css/bootstrap-datepicker3.css")" />
    <link rel="stylesheet" href="@Url.Content("~/assets/themes/vendor/pnotify/pnotify.custom.css")" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <!-- Theme CSS -->
    <link rel="stylesheet" href="@Url.Content("~/assets/themes/css/theme.css")" />
    <!-- Skin CSS -->
    <link rel="stylesheet" href="@Url.Content("~/assets/themes/css/skins/default.css")" />
    <link rel="stylesheet" href="@Url.Content("~/css/Loading.css")" />        

    <!-- Head Libs -->
    <script src="@Url.Content("~/assets/themes/vendor/modernizr/modernizr.js")"></script>
</head>
<body style="background-image: url(/assets/themes/img/bg_mobile.jpg);">

    <section class="body">
        <header class="header" style="height:70px;
                background-image:url('@ViewBag.Logo');
                background-size:contain;
                background-repeat:no-repeat;
                background-position:center;">
            <div class="d-md-none toggle-sidebar-left"
                 style="
    border-radius:10px;
    width:45px;
    height:45px;
    line-height:55px;
    right:5px;
    background:none;">
                <a href="@Url.Action("SignOut","Auth")">
                    <i class="fas fa-2x fa-sign-out-alt"></i>
                </a>
            </div>
        </header>
        <div class="inner-wrapper">
            <section role="main" class="container-fluid p-0">
                @RenderBody()
            </section>
        </div>
    </section>

    <script src="@Url.Content("~/assets/themes/vendor/jquery/jquery.min.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/jquery-browser-mobile/jquery.browser.mobile.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/popper/umd/popper.min.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/bootstrap/js/bootstrap.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/common/common.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/nanoscroller/nanoscroller.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/magnific-popup/jquery.magnific-popup.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/moment/moment.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/jquery-confirm/js/jquery-confirm.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/pnotify/pnotify.custom.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/select2/js/select2.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/ios7-switch/ios7-switch.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/autosize/autosize.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/inputmask/jquery.inputmask.bundle.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/jquery-validation/jquery.validate.js")"></script>
    <script src="@Url.Content("~/assets/themes/vendor/bootstrap-wizard/jquery.bootstrap.wizard.js")"></script>
    <!-- Theme Base, Components and Settings -->
    <script src="@Url.Content("~/assets/themes/vendor/isotope/isotope.js")"></script>
    <script src="@Url.Content("~/assets/themes/js/theme.js")"></script>
    <!-- Theme Initialization Files -->
    <script src="@Url.Content("~/assets/themes/js/theme.init.js")"></script>
    <script src="@Url.Content("~/js/Utils.js")"></script>
    <script src="@Url.Content("~/js/site.js")"></script>
    @RenderSection("Scripts", false)
    <script>
        $(window).scroll(function () {
            var height = $(window).scrollTop();
            if (height > 100) {
                $(".btn-top").fadeIn();
            } else {
                $(".btn-top").fadeOut();
            }
        });
        $(document).ready(function () {
            $(".btn-top").click(function (e) {
                e.preventDefault();
                $("html, body").animate({ scrollTop: 0 }, "slow");
                return false;
            });

            $(".go-back").click(function (e) {
                var last_url = document.referrer;
                var current_url = $(location).attr("href");
                if (last_url === current_url) {
                    window.history.back(-2);
                } else {
                    window.location.href = last_url;
                }
            });

            //$("#btnSms").hide();    //.click(function (e) { e.stopPropagation(); });
            //$("#btnCall").hide();   //.click(function (e) { e.stopPropagation(); });

            Utils.LoadOut();
        });
    </script>
</body>
</html>