_Desktop/Desktop/Models/Setting/Branch_Data.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;


namespace Desktop
{
    public class Branch_Data
    {
       
        public static List<Branch_Model> List(string PartnerNumber)
        {
            DataTable zTable = new DataTable();
            string zSQL = "SELECT  * FROM HRM_Branch WHERE RecordStatus != 99 AND PartnerNumber = @PartnerNumber ORDER BY Rank";
            string zConnectionString = Helper.ConnectionString;
            try
            {
                SqlConnection zConnect = new SqlConnection(zConnectionString);
                zConnect.Open();
                SqlCommand zCommand = new SqlCommand(zSQL, zConnect);
                zCommand.Parameters.Add("@PartnerNumber", SqlDbType.NVarChar).Value = PartnerNumber;
                SqlDataAdapter zAdapter = new SqlDataAdapter(zCommand);
                zAdapter.Fill(zTable);
                zCommand.Dispose();
                zConnect.Close();
            }
            catch (Exception ex)
            {
                string zstrMessage = ex.ToString();
            }
            List<Branch_Model> zList = new List<Branch_Model>();
            if (zTable.Rows.Count > 0)
            {

                foreach (DataRow r in zTable.Rows)
                {
                    zList.Add(new Branch_Model()
                    {
                        BranchKey = r["BranchKey"].ToInt(),
                        BranchName = r["BranchName"].ToString(),
                        BranchID = r["BranchID"].ToString(),
                        Address = r["Address"].ToString(),
                        Description = r["Description"].ToString(),
                        Rank = r["Rank"].ToInt(),
                    });
                }
            }
            return zList;
        }
    }
}

_Desktop/Desktop/Models/Setting/Branch_Model.cs
using System;
namespace Desktop
{
    public class Branch_Model
    {
        #region [ Field Name ]
        private int _BranchKey = 0;
        private string _BranchName = "";
        private string _BranchID = "";
        private string _Address = "";
        private string _Ward = "";
        private string _District = "";
        private string _Province = "";
        private string _Country = "";
        private string _Description = "";
        private int _Rank = 0;
        private string _PartnerNumber = "";
        private int _RecordStatus = 0;
        private DateTime _CreatedOn = DateTime.MinValue;
        private string _CreatedBy = "";
        private string _CreatedName = "";
        private DateTime _ModifiedOn = DateTime.MinValue;
        private string _ModifiedBy = "";
        private string _ModifiedName = "";        
        #endregion

        #region [ Properties ]
        public int BranchKey
        {
            get { return _BranchKey; }
            set { _BranchKey = value; }
        }
        public string BranchName
        {
            get { return _BranchName; }
            set { _BranchName = value; }
        }
        public string BranchID
        {
            get { return _BranchID; }
            set { _BranchID = value; }
        }
        public string Address
        {
            get { return _Address; }
            set { _Address = value; }
        }
        public string Ward
        {
            get { return _Ward; }
            set { _Ward = value; }
        }
        public string District
        {
            get { return _District; }
            set { _District = value; }
        }
        public string Province
        {
            get { return _Province; }
            set { _Province = value; }
        }
        public string Country
        {
            get { return _Country; }
            set { _Country = value; }
        }
        public string Description
        {
            get { return _Description; }
            set { _Description = value; }
        }
        public int Rank
        {
            get { return _Rank; }
            set { _Rank = value; }
        }
        public string PartnerNumber
        {
            get { return _PartnerNumber; }
            set { _PartnerNumber = value; }
        }
        public int RecordStatus
        {
            get { return _RecordStatus; }
            set { _RecordStatus = value; }
        }
        public DateTime CreatedOn
        {
            get { return _CreatedOn; }
            set { _CreatedOn = value; }
        }
        public string CreatedBy
        {
            get { return _CreatedBy; }
            set { _CreatedBy = value; }
        }
        public string CreatedName
        {
            get { return _CreatedName; }
            set { _CreatedName = value; }
        }
        public DateTime ModifiedOn
        {
            get { return _ModifiedOn; }
            set { _ModifiedOn = value; }
        }
        public string ModifiedBy
        {
            get { return _ModifiedBy; }
            set { _ModifiedBy = value; }
        }
        public string ModifiedName
        {
            get { return _ModifiedName; }
            set { _ModifiedName = value; }
        }      
        #endregion
    }
}

_Desktop/Desktop/Models/Setting/Group_Data.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;

namespace Desktop
{
    public class Group_Data
    {
        public static List<Group_Model> List(string PartnerNumber, out string Message)
        {
            DataTable zTable = new DataTable();
            string zSQL = "SELECT * FROM SYS_Group WHERE RecordStatus != 99 AND PartnerNumber = @PartnerNumber ";
            string zConnectionString = Helper.ConnectionString;
            try
            {
                SqlConnection zConnect = new SqlConnection(zConnectionString);
                zConnect.Open();
                SqlCommand zCommand = new SqlCommand(zSQL, zConnect);
                zCommand.Parameters.Add("@PartnerNumber", SqlDbType.NVarChar).Value = PartnerNumber;
                SqlDataAdapter zAdapter = new SqlDataAdapter(zCommand);
                zAdapter.Fill(zTable);
                zCommand.Dispose();
                zConnect.Close(); Message = string.Empty;
            }
            catch (Exception ex)
            {
                Message = ex.ToString();
            }
            List<Group_Model> zList = new List<Group_Model>();
            foreach (DataRow r in zTable.Rows)
            {
                zList.Add(new Group_Model()
                {
                    GroupKey = r["GroupKey"].ToString(),
                    GroupName = r["GroupName"].ToString(),
                    Description = r["Description"].ToString(),
                    IsPublish = r["IsPublish"].ToBool(),
                    Module = r["Module"].ToString(),
                    PartnerNumber = r["PartnerNumber"].ToString(),
                    RecordStatus = r["RecordStatus"].ToInt(),
                    CreatedOn = (r["CreatedOn"] == DBNull.Value ? DateTime.MinValue : (DateTime)r["CreatedOn"]),
                    CreatedBy = r["CreatedBy"].ToString(),
                    CreatedName = r["CreatedName"].ToString(),
                    ModifiedOn = (r["ModifiedOn"] == DBNull.Value ? DateTime.MinValue : (DateTime)r["ModifiedOn"]),
                    ModifiedBy = r["ModifiedBy"].ToString(),
                    ModifiedName = r["ModifiedName"].ToString(),
                });
            }
            return zList;
        }
    }
}

_Desktop/Desktop/Controllers/SettingController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Globalization;
using Desktop;
using Desktop.Controllers;

namespace TN_Setting.Controllers
{
    public class SettingController : BaseController
    {
        public IActionResult Index()
        {
            return View();
        }

        #region [Branch_Setting]
        public IActionResult Branch()
        {
            ViewBag.ListBranch = Branch_Data.List(UserLog.PartnerNumber);
            return View();
        }
        public JsonResult Save_Branch(string BranchKey = "", string BranchID = "", string BranchName = "", string Address = "", string Description = "", int Rank = 0)
        {
            var zResult = new ServerResult();
            var zInfo = new Branch_Info();
            var zModel = new Branch_Model();

            BranchKey = BranchKey ?? "0";
            BranchID = BranchID ?? "";
            BranchName = BranchName ?? "";
            Address = Address ?? "";
            Description = Description ?? "";

            zModel.PartnerNumber = UserLog.PartnerNumber;
            zModel.BranchKey = BranchKey.ToInt();
            zModel.BranchID = BranchID.Trim();
            zModel.BranchName = BranchName.Trim();
            zModel.Address = Address.Trim();
            zModel.Rank = Rank;
            zModel.Description = Description.Trim();
            zModel.CreatedBy = UserLog.UserKey;
            zModel.CreatedName = UserLog.Employee.FullName;
            zModel.ModifiedBy = UserLog.UserKey;
            zModel.ModifiedName = UserLog.Employee.FullName;


            zModel.ClearNullable();
            if (BranchKey=="0")
            {
                zInfo.Branch = zModel;
                zInfo.Create_ServerKey();
            }
            else
            {
                zInfo.Branch = zModel;
                zInfo.Update();
            }

            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                zResult.Success = true;
                return Json(zResult);
            }
            else
            {
                zResult.Success = false;
                zResult.Message = zInfo.Message.GetFirstLine();
                return Json(zResult);
            }
        }
        public JsonResult Edit_Branch(string BranchKey)
        {
            var zResult = new ServerResult();
            var zInfo = new Branch_Info(BranchKey);
            var zModel = zInfo.Branch;
            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                zResult.Success = true;
                zResult.Data = JsonConvert.SerializeObject(zModel);
            }
            else
            {
                zResult.Success = false;
                zResult.Message = zInfo.Message.GetFirstLine();
            }
            return Json(zResult);
        }
        public JsonResult Delete_Branch(string BranchKey = "")
        {
            var zResult = new ServerResult();
            var zInfo = new Branch_Info();
            BranchKey = BranchKey ?? "0";
            zInfo.Branch.BranchKey = BranchKey.ToInt();
            zInfo.Delete();

            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                zResult.Success = true;
                return Json(zResult);
            }
            else
            {
                zResult.Success = false;
                zResult.Message = zInfo.Message.GetFirstLine();
                return Json(zResult);
            }
        }
        #endregion

        #region [Depart_Setting]
        public IActionResult Department()
        {
            ViewBag.ListDepartment = Department_Data.List(UserLog.PartnerNumber);
            ViewBag.ListBranch = Branch_Data.List(UserLog.PartnerNumber);
            return View();
        }
        public JsonResult Save_Department(string DepartmentKey = "", string DepartmentID = "", string DepartmentName = "", string Description = "", int Rank = 0, string BranchKey = "0", string BranchName = "")
        {
            var zResult = new ServerResult();
            var zInfo = new Department_Info();
            var zModel = new Department_Model();

            DepartmentKey = DepartmentKey ?? "0";
            DepartmentID = DepartmentID ?? "";
            DepartmentName = DepartmentName ?? "";
            Description = Description ?? "";

            zModel.PartnerNumber = UserLog.PartnerNumber;
            zModel.DepartmentKey = DepartmentKey.ToInt();
            zModel.DepartmentID = DepartmentID.Trim();
            zModel.DepartmentName = DepartmentName.Trim();
            zModel.Description = Description.Trim();
            zModel.Rank = Rank;
            zModel.BranchKey = BranchKey.ToInt();
            zModel.BranchName = BranchName;
            zModel.CreatedBy = UserLog.UserKey;
            zModel.CreatedName = UserLog.Employee.FullName;
            zModel.ModifiedBy = UserLog.UserKey;
            zModel.ModifiedName = UserLog.Employee.FullName;

            zModel.ClearNullable();
            if (DepartmentKey == "0")
            {
                zInfo.Department = zModel;
                zInfo.Create_ServerKey();
            }
            else
            {
                zInfo.Department = zModel;
                zInfo.Update();
            }

            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                zResult.Success = true;
                return Json(zResult);
            }
            else
            {
                zResult.Success = false;
                zResult.Message = zInfo.Message.GetFirstLine();
                return Json(zResult);
            }
        }
        public JsonResult Edit_Department(string DepartmentKey)
        {
            var zResult = new ServerResult();
            var zInfo = new Department_Info(DepartmentKey);
            var zModel = zInfo.Department;
            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                zResult.Success = true;
                zResult.Data = JsonConvert.SerializeObject(zModel);
                return Json(zResult);
            }
            else
            {
                zResult.Success = false;
                zResult.Message = zInfo.Message.GetFirstLine();
                return Json(zResult);
            }
        }
        public JsonResult Delete_Department(string DepartmentKey = "")
        {
            var zResult = new ServerResult();
            var zInfo = new Department_Info();
            DepartmentKey = DepartmentKey ?? "0";
            zInfo.Department.DepartmentKey = DepartmentKey.ToInt();
            zInfo.Delete();

            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                zResult.Success = true;
                return Json(zResult);
            }
            else
            {
                zResult.Success = false;
                zResult.Message = zInfo.Message.GetFirstLine();
                return Json(zResult);
            }
        }
        #endregion

        #region [Position_Setting]
        public IActionResult Position()
        {
            ViewBag.Position = Position_Data.List(UserLog.PartnerNumber);
            return View();
        }
        public JsonResult Save_Position(int PositionKey = 0, string PositionID = "", string PositionNameVN = "", string Description = "", int Rank = 0)
        {
            var zResult = new ServerResult();
            var zInfo = new Position_Info();
            var zModel = new Position_Model
            {
                PartnerNumber = UserLog.PartnerNumber,
                PositionKey = PositionKey,
                PositionID = PositionID,
                PositionNameVN = PositionNameVN,
                Rank = Rank,
                Description = Description,

                CreatedBy = UserLog.UserKey,
                CreatedName = UserLog.Employee.FullName,
                ModifiedBy = UserLog.UserKey,
                ModifiedName = UserLog.Employee.FullName
            };

            zModel.ClearNullable();
            if (PositionKey == 0)
            {
                zInfo.Position = zModel;
                zInfo.Create_ServerKey();
            }
            else
            {
                zInfo.Position = zModel;
                zInfo.Update();
            }

            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                zResult.Success = true;
                return Json(zResult);
            }
            else
            {
                zResult.Success = false;
                zResult.Message = zInfo.Message.GetFirstLine();
                return Json(zResult);
            }
        }
        public JsonResult Edit_Position(int PositionKey)
        {
            var zResult = new ServerResult();
            var zInfo = new Position_Info(PositionKey);

            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                zResult.Success = true;
                zResult.Data = JsonConvert.SerializeObject(zInfo.Position);
            }
            else
            {
                zResult.Success = false;
                zResult.Message = zInfo.Message.GetFirstLine();
            }

            return Json(zResult);
        }
        public JsonResult Delete_Position(int PositionKey)
        {
            var zResult = new ServerResult();
            var zInfo = new Position_Info();
            zInfo.Position.PositionKey = PositionKey;
            zInfo.Delete();

            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                zResult.Success = true;
                return Json(zResult);
            }
            else
            {
                zResult.Success = false;
                zResult.Message = zInfo.Message.GetFirstLine();
                return Json(zResult);

_Desktop/Desktop/Views/Setting/Branch.cshtml
@using Desktop;
@{
    ViewData["Title"] = "Branch";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var _ListBranch = new List<Branch_Model>();
    if (ViewBag.ListBranch != null)
    {
        _ListBranch = ViewBag.ListBranch as List<Branch_Model>;
    }
}

<header class="page-header">
    <h2>Danh sách chi nhánh (Cập nhật thông tin)</h2>

    <div class="right-wrapper text-right">
        <ol class="breadcrumbs">
            <li>
                <a href="index.html">
                    <i class="fas fa-home"></i>
                </a>
            </li>
            <li></li>
        </ol>
    </div>
</header>
<div class="row">
    <div class="col-md-12">
        <div class="card border ">
            <div class="card-header ">

            </div>
            <div class="card-body ">
                <table class="table Custom table-sm">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Mã chi nhánh</th>
                            <th>Tên chi nhánh</th>
                            <th>Địa chỉ</th>
                            <th>Ghi chú</th>
                            <th>Sắp xếp</th>
                            <th class="text-right">
                                <button class=" btn btn-info" type="button" onclick="Edit('')">
                                    <i class="fa fa-plus"></i>
                                    Thêm mới
                                </button>
                            </th>
                        </tr>
                    </thead>
                    <tbody id="tblBody">
                        @if (_ListBranch != null && _ListBranch.Count > 0)
                        {
                            for (int i = 0; i < _ListBranch.Count; i++)
                            {
                                Branch_Model Model = _ListBranch[i];

                                <tr key="@Model.BranchKey">
                                    <td>@(i + 1)</td>
                                    <td>@Model.BranchID</td>
                                    <td>@Model.BranchName</td>
                                    <td>@Model.Address</td>
                                    <td>@Model.Description</td>
                                    <td>@Model.Rank</td>
                                    <td class="text-right">
                                        <button type="button" class="btn btn-outline-primary btn-sm " onclick="Edit('@Model.BranchKey')">
                                            <i class="far fa-edit"></i>
                                        </button>
                                        <button type="button" class="btn btn-outline-danger btn-sm" onclick="Delete('@Model.BranchKey')">
                                            <i class="fas fa-trash"></i>
                                        </button>
                                    </td>
                                </tr>
                            }
                        }
                        else
                        {
                            <tr>
                                <td colspan="7">
                                    <div class="alert alert-primary">
                                        <strong>Bạn chưa cập nhật, hoặc không tìm thấy dữ liệu phù hợp !</strong>.
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="card-footer ">
            </div>
        </div>

    </div>
</div>
<div id="modalEdit" class="zoom-anim-dialog modal-block modal-header-color modal-block-info mfp-hide">
    <div class="card border ">
        <div class="card-header">
            <h2 class="card-title">Chi nhánh</h2>
        </div>
        <div class="card-body ">
            <div class="form-group row">
                <label for="departmentid" class="col-lg-5 col-xl-3 control-label text-lg-right">Mã chi nhánh</label>
                <div class="col-lg-7 col-xl-9">
                    <input type="text" class="form-control" id="txt_BranchID" placeholder="" required="">
                </div>
            </div>
            <div class="form-group row">
                <label for="deparmentname" class="col-lg-5 col-xl-3 control-label text-lg-right">Tên chi nhánh</label>
                <div class="col-lg-7 col-xl-9">
                    <input type="text" class="form-control" id="txt_BranchName" placeholder="" required="">
                </div>
            </div>
            <div class="form-group row">
                <label for="deparmentname" class="col-lg-5 col-xl-3 control-label text-lg-right">Địa chỉ</label>
                <div class="col-lg-7 col-xl-9">
                    <textarea type="text" class="form-control" id="txt_Address" placeholder="" data-plugin-textarea-autosize rows="2"></textarea>
                </div>
            </div>
            <div class="form-group row">
                <label for="description" class="col-lg-5 col-xl-3 control-label text-lg-right">Ghi chú</label>
                <div class="col-lg-7 col-xl-9">
                    <input type="text" class="form-control" id="txt_Description" placeholder="Ghi chú" required="">
                </div>
            </div>
            <div class="form-group row">
                <label for="username" class="col-lg-5 col-xl-3 control-label text-lg-right">Thứ tự hiển thị</label>
                <div class="col-lg-7 col-xl-9">
                    <input type="number" class="form-control" id="txt_Rank" value="0" placeholder="">
                </div>
            </div>
        </div>
        <div class="card-footer  text-center">
            <button id="btn_Cancel" type="button" class="btn btn-outline-secondary modal-dismiss">
                <i class="far fa-times-circle"></i>
                Đóng
            </button>
            <button id="btn_Save" type="button" class="btn btn-outline-primary" onclick="Save()">
                <i class="far fa-save"></i>
                Cập nhật
            </button>
        </div>
    </div>
    <input id="txt_BranchKey" type="hidden" name="BranchKey" value="0" />
</div>

@section scripts {
    <script>
        var URL_Edit = "@Url.Action("Edit_Branch", "Setting")";
        var URL_Delete = "@Url.Action("Delete_Branch", "Setting")";
        var URL_Save = "@Url.Action("Save_Branch", "Setting")";

        $(document).ready(function () {

        });

        function Save() {
            var BranchKey = $("#txt_BranchKey").val();
            var BranchID = $("#txt_BranchID").val();
            var BranchName = $("#txt_BranchName").val();
            var Address = $("#txt_Address").val();
            var Description = $("#txt_Description").val();
            var Rank = $("#txt_Rank").val();
            $.ajax({
                url: URL_Save,
                type: "POST",
                data: {
                    "BranchKey": BranchKey,
                    "BranchID": BranchID,
                    "BranchName": BranchName,
                    "Address": Address,
                    "Description": Description,
                    "Rank": Rank,
                },
                beforeSend: function () {

                },
                success: function (r) {
                    if (r.success) {
                        location.reload();
                    }
                    else {
                        Utils.OpenNotify(r.Message, "Thông báo", "error");
                    }
                },
                error: function (err) {
                    Utils.OpenNotify(err.responseText, "Thông báo", "error");
                },
                complete: function () {

                }
            });
        }
        function Edit(BranchKey) {
            Utils.OpenMagnific("#modalEdit");
            if (BranchKey != "") {
                $.ajax({
                    url: URL_Edit,
                    type: "GET",
                    data: {
                        "BranchKey": BranchKey
                    },
                    beforeSend: function () {

                    },
                    success: function (r) {
                        if (r.success) {
                            var obj = JSON.parse(r.data);

                            $("#txt_BranchKey").val(obj.BranchKey);
                            $("#txt_BranchID").val(obj.BranchID);
                            $("#txt_BranchName").val(obj.BranchName);
                            $("#txt_Address").val(obj.Address);
                            $("#txt_Description").val(obj.Description);
                            $("#txt_Rank").val(obj.Rank);
                        }
                        else {
                            Utils.OpenNotify(r.Message, "Thông báo", "error");
                        }
                    },
                    error: function (err) {
                        Utils.OpenNotify(err.responseText, "Thông báo", "error");
                    },
                    complete: function () {

                    }
                });
            }
            else {
                Utils.ClearUI("#modalEdit");
                $("#txt_BranchKey").val("");
                $("#txt_Rank").val(0);
            }
        }
        function Delete(BranchKey) {
            $.confirm({
                type: "red",
                typeAnimated: true,
                title: "Cảnh báo !.",
                content: "Bạn có chắc xóa thông tin này ?.",
                buttons: {
                    confirm: {
                        text: "Đồng ý",
                        btnClass: "btn-red",
                        action: function () {
                            $.ajax({
                                url: URL_Delete,
                                type: "POST",
                                data: {
                                    "BranchKey": BranchKey
                                },
                                beforeSend: function () {

                                },
                                success: function (r) {
                                    if (r.success) {
                                        $("tr[key='" + BranchKey + "']").fadeOut('slow', function () {
                                            $(this).remove();
                                            console.log("đã xóa");
                                        });
                                    }
                                    else {
                                        Utils.OpenNotify(r.Message, "Thông báo", "error");
                                    }
                                },
                                error: function (err) {
                                    Utils.OpenNotify(err.responseText, "Thông báo", "error");
                                },
                                complete: function () {

                                }
                            });
                        }
                    },
                    cancel: {
                        text: "Hủy",
                    }
                }
            });
        }

    </script>
}